FROM python:3.11

ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY backend/requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

COPY ./backend /app

# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]