# Generated by Django 5.0 on 2024-08-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_remove_user_username_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
