# Generated by Django 5.0 on 2024-08-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_add',
            field=models.BooleanField(default=False),
        ),
    ]
