# Dockerfile in the front directory
FROM node:20-alpine

WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY front/package.json /app/package.json
COPY front/package-lock.json /app/package-lock.json

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY front /app/

# Expose the port that the app runs on
EXPOSE 5173

# Command to run the app
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
